// Generated by `wit-bindgen` 0.46.0. DO NOT EDIT!
// Options used:
//   * with "wasi:cli/environment@0.3.0-rc-2025-09-16" = "crate::cli::environment"
//   * with "wasi:cli/exit@0.3.0-rc-2025-09-16" = "crate::cli::exit"
//   * with "wasi:cli/stdin@0.3.0-rc-2025-09-16" = "crate::cli::stdin"
//   * with "wasi:cli/stdout@0.3.0-rc-2025-09-16" = "crate::cli::stdout"
//   * with "wasi:cli/stderr@0.3.0-rc-2025-09-16" = "crate::cli::stderr"
//   * with "wasi:cli/types@0.3.0-rc-2025-09-16" = "crate::cli::types"
//   * with "wasi:cli/terminal-input@0.3.0-rc-2025-09-16" = "crate::cli::terminal_input"
//   * with "wasi:cli/terminal-output@0.3.0-rc-2025-09-16" = "crate::cli::terminal_output"
//   * with "wasi:cli/terminal-stdin@0.3.0-rc-2025-09-16" = "crate::cli::terminal_stdin"
//   * with "wasi:cli/terminal-stdout@0.3.0-rc-2025-09-16" = "crate::cli::terminal_stdout"
//   * with "wasi:cli/terminal-stderr@0.3.0-rc-2025-09-16" = "crate::cli::terminal_stderr"
//   * with "wasi:clocks/monotonic-clock@0.3.0-rc-2025-09-16" = "crate::clocks::monotonic_clock"
//   * with "wasi:clocks/wall-clock@0.3.0-rc-2025-09-16" = "crate::clocks::wall_clock"
//   * with "wasi:clocks/types@0.3.0-rc-2025-09-16" = "crate::clocks::types"
//   * with "wasi:filesystem/types@0.3.0-rc-2025-09-16" = "crate::filesystem::types"
//   * with "wasi:filesystem/preopens@0.3.0-rc-2025-09-16" = "crate::filesystem::preopens"
//   * with "wasi:random/random@0.3.0-rc-2025-09-16" = "crate::random::random"
//   * with "wasi:random/insecure@0.3.0-rc-2025-09-16" = "crate::random::insecure"
//   * with "wasi:random/insecure-seed@0.3.0-rc-2025-09-16" = "crate::random::insecure_seed"
//   * with "wasi:sockets/types@0.3.0-rc-2025-09-16" = "crate::sockets::types"
//   * with "wasi:sockets/ip-name-lookup@0.3.0-rc-2025-09-16" = "crate::sockets::ip_name_lookup"
//   * type_section_suffix: "rust-wasip3-0.2.2+wasi-0.3.0-rc-2025-09-16-from-crates-io-command-world"
//   * default-bindings-module: "$crate"
//   * export-macro-name: _export_command
//   * pub-export-macro
#[allow(unfulfilled_lint_expectations, unused_imports)]
use crate::cli::environment as __with_name0;
#[allow(unfulfilled_lint_expectations, unused_imports)]
use crate::cli::exit as __with_name1;
#[allow(unfulfilled_lint_expectations, unused_imports)]
use crate::cli::types as __with_name2;
#[allow(unfulfilled_lint_expectations, unused_imports)]
use crate::cli::stdin as __with_name3;
#[allow(unfulfilled_lint_expectations, unused_imports)]
use crate::cli::stdout as __with_name4;
#[allow(unfulfilled_lint_expectations, unused_imports)]
use crate::cli::stderr as __with_name5;
#[allow(unfulfilled_lint_expectations, unused_imports)]
use crate::cli::terminal_input as __with_name6;
#[allow(unfulfilled_lint_expectations, unused_imports)]
use crate::cli::terminal_output as __with_name7;
#[allow(unfulfilled_lint_expectations, unused_imports)]
use crate::cli::terminal_stdin as __with_name8;
#[allow(unfulfilled_lint_expectations, unused_imports)]
use crate::cli::terminal_stdout as __with_name9;
#[allow(unfulfilled_lint_expectations, unused_imports)]
use crate::cli::terminal_stderr as __with_name10;
#[allow(unfulfilled_lint_expectations, unused_imports)]
use crate::clocks::types as __with_name11;
#[allow(unfulfilled_lint_expectations, unused_imports)]
use crate::clocks::monotonic_clock as __with_name12;
#[allow(unfulfilled_lint_expectations, unused_imports)]
use crate::clocks::wall_clock as __with_name13;
#[allow(unfulfilled_lint_expectations, unused_imports)]
use crate::filesystem::types as __with_name14;
#[allow(unfulfilled_lint_expectations, unused_imports)]
use crate::filesystem::preopens as __with_name15;
#[allow(unfulfilled_lint_expectations, unused_imports)]
use crate::sockets::types as __with_name16;
#[allow(unfulfilled_lint_expectations, unused_imports)]
use crate::sockets::ip_name_lookup as __with_name17;
#[allow(unfulfilled_lint_expectations, unused_imports)]
use crate::random::random as __with_name18;
#[allow(unfulfilled_lint_expectations, unused_imports)]
use crate::random::insecure as __with_name19;
#[allow(unfulfilled_lint_expectations, unused_imports)]
use crate::random::insecure_seed as __with_name20;
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod wasi {
        pub mod cli {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod run {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_async_run_cabi<T: Guest>() -> i32 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                        wit_bindgen::rt::async_support::start_task(async move {
                            let _task_cancel = wit_bindgen::rt::async_support::TaskCancelOnDrop::new();
                            let result0 = &{ T::run().await };
                            let result1 = match result0 {
                                Ok(_) => 0i32,
                                Err(_) => 1i32,
                            };
                            #[cfg(target_arch = "wasm32")]
                            #[link(
                                wasm_import_module = "[export]wasi:cli/run@0.3.0-rc-2025-09-16"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[task-return][async]run"]
                                fn wit_import2(_: i32);
                            }
                            #[cfg(not(target_arch = "wasm32"))]
                            unsafe extern "C" fn wit_import2(_: i32) {
                                unreachable!()
                            }
                            _task_cancel.forget();
                            wit_import2(result1);
                        })
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __callback_async_run(
                    event0: u32,
                    event1: u32,
                    event2: u32,
                ) -> u32 {
                    unsafe {
                        wit_bindgen::rt::async_support::callback(event0, event1, event2)
                    }
                }
                pub trait Guest {
                    /// Run the program.
                    #[allow(async_fn_in_trait)]
                    async fn run() -> Result<(), ()>;
                }
                #[doc(hidden)]
                #[macro_export]
                macro_rules! __export_wasi_cli_run_0_3_0_rc_2025_09_16_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "[async-lift]wasi:cli/run@0.3.0-rc-2025-09-16#[async]run")]
                        unsafe extern "C" fn export_async_run() -> i32 { unsafe {
                        $($path_to_types)*:: _export_async_run_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "[callback][async-lift]wasi:cli/run@0.3.0-rc-2025-09-16#[async]run")]
                        unsafe extern "C" fn _callback_async_run(event0 : u32, event1 :
                        u32, event2 : u32) -> u32 { unsafe { $($path_to_types)*::
                        __callback_async_run(event0, event1, event2) } } };
                    };
                }
                #[doc(hidden)]
                pub use __export_wasi_cli_run_0_3_0_rc_2025_09_16_cabi;
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen::rt::run_ctors_once();
    }
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! _export_command{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// _export_command!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
#[macro_export]
macro_rules! __export_command_impl {
    ($ty:ident) => {
        $crate::_export_command!($ty with_types_in $crate);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::wasi::cli::run::__export_wasi_cli_run_0_3_0_rc_2025_09_16_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::wasi::cli::run); const _ : () =
        { #[rustfmt::skip] #[cfg(target_arch = "wasm32")] #[unsafe (link_section =
        "component-type:wit-bindgen:0.46.0:wasi:cli@0.3.0-rc-2025-09-16:command:imports and exportsrust-wasip3-0.2.2+wasi-0.3.0-rc-2025-09-16-from-crates-io-command-world")]
        #[doc(hidden)] #[allow(clippy::octal_escapes)] pub static
        __WIT_BINDGEN_COMPONENT_TYPE : [u8; 8243] = *
        b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xb5?\x01A\x02\x01A4\x01\
B\x0a\x01o\x02ss\x01p\0\x01@\0\0\x01\x04\0\x0fget-environment\x01\x02\x01ps\x01@\
\0\0\x03\x04\0\x0dget-arguments\x01\x04\x01ks\x01@\0\0\x05\x04\0\x0fget-initial-\
cwd\x01\x06\x03\0(wasi:cli/environment@0.3.0-rc-2025-09-16\x05\0\x01B\x03\x01j\0\
\0\x01@\x01\x06status\0\x01\0\x04\0\x04exit\x01\x01\x03\0!wasi:cli/exit@0.3.0-rc\
-2025-09-16\x05\x01\x01B\x02\x01m\x03\x02io\x15illegal-byte-sequence\x04pipe\x04\
\0\x0aerror-code\x03\0\0\x03\0\"wasi:cli/types@0.3.0-rc-2025-09-16\x05\x02\x02\x03\
\0\x02\x0aerror-code\x01B\x08\x02\x03\x02\x01\x03\x04\0\x0aerror-code\x03\0\0\x01\
f\x01}\x01j\0\x01\x01\x01e\x01\x03\x01o\x02\x02\x04\x01@\0\0\x05\x04\0\x0fread-v\
ia-stream\x01\x06\x03\0\"wasi:cli/stdin@0.3.0-rc-2025-09-16\x05\x04\x01B\x06\x02\
\x03\x02\x01\x03\x04\0\x0aerror-code\x03\0\0\x01f\x01}\x01j\0\x01\x01\x01@\x01\x04\
data\x02\0\x03\x04\0\x17[async]write-via-stream\x01\x04\x03\0#wasi:cli/stdout@0.\
3.0-rc-2025-09-16\x05\x05\x01B\x06\x02\x03\x02\x01\x03\x04\0\x0aerror-code\x03\0\
\0\x01f\x01}\x01j\0\x01\x01\x01@\x01\x04data\x02\0\x03\x04\0\x17[async]write-via\
-stream\x01\x04\x03\0#wasi:cli/stderr@0.3.0-rc-2025-09-16\x05\x06\x01B\x01\x04\0\
\x0eterminal-input\x03\x01\x03\0+wasi:cli/terminal-input@0.3.0-rc-2025-09-16\x05\
\x07\x01B\x01\x04\0\x0fterminal-output\x03\x01\x03\0,wasi:cli/terminal-output@0.\
3.0-rc-2025-09-16\x05\x08\x02\x03\0\x06\x0eterminal-input\x01B\x06\x02\x03\x02\x01\
\x09\x04\0\x0eterminal-input\x03\0\0\x01i\x01\x01k\x02\x01@\0\0\x03\x04\0\x12get\
-terminal-stdin\x01\x04\x03\0+wasi:cli/terminal-stdin@0.3.0-rc-2025-09-16\x05\x0a\
\x02\x03\0\x07\x0fterminal-output\x01B\x06\x02\x03\x02\x01\x0b\x04\0\x0fterminal\
-output\x03\0\0\x01i\x01\x01k\x02\x01@\0\0\x03\x04\0\x13get-terminal-stdout\x01\x04\
\x03\0,wasi:cli/terminal-stdout@0.3.0-rc-2025-09-16\x05\x0c\x01B\x06\x02\x03\x02\
\x01\x0b\x04\0\x0fterminal-output\x03\0\0\x01i\x01\x01k\x02\x01@\0\0\x03\x04\0\x13\
get-terminal-stderr\x01\x04\x03\0,wasi:cli/terminal-stderr@0.3.0-rc-2025-09-16\x05\
\x0d\x01B\x02\x01w\x04\0\x08duration\x03\0\0\x03\0%wasi:clocks/types@0.3.0-rc-20\
25-09-16\x05\x0e\x02\x03\0\x0b\x08duration\x01B\x0c\x02\x03\x02\x01\x0f\x04\0\x08\
duration\x03\0\0\x01w\x04\0\x07instant\x03\0\x02\x01@\0\0\x03\x04\0\x03now\x01\x04\
\x01@\0\0\x01\x04\0\x0eget-resolution\x01\x05\x01@\x01\x04when\x03\x01\0\x04\0\x11\
[async]wait-until\x01\x06\x01@\x01\x08how-long\x01\x01\0\x04\0\x0f[async]wait-fo\
r\x01\x07\x03\0/wasi:clocks/monotonic-clock@0.3.0-rc-2025-09-16\x05\x10\x01B\x05\
\x01r\x02\x07secondsw\x0bnanosecondsy\x04\0\x08datetime\x03\0\0\x01@\0\0\x01\x04\
\0\x03now\x01\x02\x04\0\x0eget-resolution\x01\x02\x03\0*wasi:clocks/wall-clock@0\
.3.0-rc-2025-09-16\x05\x11\x02\x03\0\x0d\x08datetime\x01BY\x02\x03\x02\x01\x12\x04\
\0\x08datetime\x03\0\0\x01w\x04\0\x08filesize\x03\0\x02\x01m\x08\x07unknown\x0cb\
lock-device\x10character-device\x09directory\x04fifo\x0dsymbolic-link\x0cregular\
-file\x06socket\x04\0\x0fdescriptor-type\x03\0\x04\x01n\x06\x04read\x05write\x13\
file-integrity-sync\x13data-integrity-sync\x14requested-write-sync\x10mutate-dir\
ectory\x04\0\x10descriptor-flags\x03\0\x06\x01n\x01\x0esymlink-follow\x04\0\x0ap\
ath-flags\x03\0\x08\x01n\x04\x06create\x09directory\x09exclusive\x08truncate\x04\
\0\x0aopen-flags\x03\0\x0a\x01w\x04\0\x0alink-count\x03\0\x0c\x01k\x01\x01r\x06\x04\
type\x05\x0alink-count\x0d\x04size\x03\x15data-access-timestamp\x0e\x1bdata-modi\
fication-timestamp\x0e\x17status-change-timestamp\x0e\x04\0\x0fdescriptor-stat\x03\
\0\x0f\x01q\x03\x09no-change\0\0\x03now\0\0\x09timestamp\x01\x01\0\x04\0\x0dnew-\
timestamp\x03\0\x11\x01r\x02\x04type\x05\x04names\x04\0\x0fdirectory-entry\x03\0\
\x13\x01m$\x06access\x07already\x0ebad-descriptor\x04busy\x08deadlock\x05quota\x05\
exist\x0efile-too-large\x15illegal-byte-sequence\x0bin-progress\x0binterrupted\x07\
invalid\x02io\x0cis-directory\x04loop\x0etoo-many-links\x0cmessage-size\x0dname-\
too-long\x09no-device\x08no-entry\x07no-lock\x13insufficient-memory\x12insuffici\
ent-space\x0dnot-directory\x09not-empty\x0fnot-recoverable\x0bunsupported\x06no-\
tty\x0eno-such-device\x08overflow\x0dnot-permitted\x04pipe\x09read-only\x0cinval\
id-seek\x0etext-file-busy\x0ccross-device\x04\0\x0aerror-code\x03\0\x15\x01m\x06\
\x06normal\x0asequential\x06random\x09will-need\x09dont-need\x08no-reuse\x04\0\x06\
advice\x03\0\x17\x01r\x02\x05lowerw\x05upperw\x04\0\x13metadata-hash-value\x03\0\
\x19\x04\0\x0adescriptor\x03\x01\x01h\x1b\x01f\x01}\x01j\0\x01\x16\x01e\x01\x1e\x01\
o\x02\x1d\x1f\x01@\x02\x04self\x1c\x06offset\x03\0\x20\x04\0\"[method]descriptor\
.read-via-stream\x01!\x01@\x03\x04self\x1c\x04data\x1d\x06offset\x03\0\x1e\x04\0\
)[async\x20method]descriptor.write-via-stream\x01\"\x01@\x02\x04self\x1c\x04data\
\x1d\0\x1e\x04\0*[async\x20method]descriptor.append-via-stream\x01#\x01@\x04\x04\
self\x1c\x06offset\x03\x06length\x03\x06advice\x18\0\x1e\x04\0\x1f[async\x20meth\
od]descriptor.advise\x01$\x01@\x01\x04self\x1c\0\x1e\x04\0\"[async\x20method]des\
criptor.sync-data\x01%\x01j\x01\x07\x01\x16\x01@\x01\x04self\x1c\0&\x04\0\"[asyn\
c\x20method]descriptor.get-flags\x01'\x01j\x01\x05\x01\x16\x01@\x01\x04self\x1c\0\
(\x04\0![async\x20method]descriptor.get-type\x01)\x01@\x02\x04self\x1c\x04size\x03\
\0\x1e\x04\0![async\x20method]descriptor.set-size\x01*\x01@\x03\x04self\x1c\x15d\
ata-access-timestamp\x12\x1bdata-modification-timestamp\x12\0\x1e\x04\0\"[async\x20\
method]descriptor.set-times\x01+\x01f\x01\x14\x01o\x02,\x1f\x01@\x01\x04self\x1c\
\0-\x04\0'[async\x20method]descriptor.read-directory\x01.\x04\0\x1d[async\x20met\
hod]descriptor.sync\x01%\x01@\x02\x04self\x1c\x04paths\0\x1e\x04\0,[async\x20met\
hod]descriptor.create-directory-at\x01/\x01j\x01\x10\x01\x16\x01@\x01\x04self\x1c\
\00\x04\0\x1d[async\x20method]descriptor.stat\x011\x01@\x03\x04self\x1c\x0apath-\
flags\x09\x04paths\00\x04\0\x20[async\x20method]descriptor.stat-at\x012\x01@\x05\
\x04self\x1c\x0apath-flags\x09\x04paths\x15data-access-timestamp\x12\x1bdata-mod\
ification-timestamp\x12\0\x1e\x04\0%[async\x20method]descriptor.set-times-at\x01\
3\x01@\x05\x04self\x1c\x0eold-path-flags\x09\x08old-paths\x0enew-descriptor\x1c\x08\
new-paths\0\x1e\x04\0\x20[async\x20method]descriptor.link-at\x014\x01i\x1b\x01j\x01\
5\x01\x16\x01@\x05\x04self\x1c\x0apath-flags\x09\x04paths\x0aopen-flags\x0b\x05f\
lags\x07\06\x04\0\x20[async\x20method]descriptor.open-at\x017\x01j\x01s\x01\x16\x01\
@\x02\x04self\x1c\x04paths\08\x04\0$[async\x20method]descriptor.readlink-at\x019\
\x04\0,[async\x20method]descriptor.remove-directory-at\x01/\x01@\x04\x04self\x1c\
\x08old-paths\x0enew-descriptor\x1c\x08new-paths\0\x1e\x04\0\"[async\x20method]d\
escriptor.rename-at\x01:\x01@\x03\x04self\x1c\x08old-paths\x08new-paths\0\x1e\x04\
\0#[async\x20method]descriptor.symlink-at\x01;\x04\0'[async\x20method]descriptor\
.unlink-file-at\x01/\x01@\x02\x04self\x1c\x05other\x1c\0\x7f\x04\0'[async\x20met\
hod]descriptor.is-same-object\x01<\x01j\x01\x1a\x01\x16\x01@\x01\x04self\x1c\0=\x04\
\0&[async\x20method]descriptor.metadata-hash\x01>\x01@\x03\x04self\x1c\x0apath-f\
lags\x09\x04paths\0=\x04\0)[async\x20method]descriptor.metadata-hash-at\x01?\x03\
\0)wasi:filesystem/types@0.3.0-rc-2025-09-16\x05\x13\x02\x03\0\x0e\x0adescriptor\
\x01B\x07\x02\x03\x02\x01\x14\x04\0\x0adescriptor\x03\0\0\x01i\x01\x01o\x02\x02s\
\x01p\x03\x01@\0\0\x04\x04\0\x0fget-directories\x01\x05\x03\0,wasi:filesystem/pr\
eopens@0.3.0-rc-2025-09-16\x05\x15\x02\x03\0\x0c\x08duration\x01Bq\x02\x03\x02\x01\
\x16\x04\0\x08duration\x03\0\0\x01m\x0e\x07unknown\x0daccess-denied\x0dnot-suppo\
rted\x10invalid-argument\x0dout-of-memory\x07timeout\x0dinvalid-state\x14address\
-not-bindable\x0eaddress-in-use\x12remote-unreachable\x12connection-refused\x10c\
onnection-reset\x12connection-aborted\x12datagram-too-large\x04\0\x0aerror-code\x03\
\0\x02\x01m\x02\x04ipv4\x04ipv6\x04\0\x11ip-address-family\x03\0\x04\x01o\x04}}}\
}\x04\0\x0cipv4-address\x03\0\x06\x01o\x08{{{{{{{{\x04\0\x0cipv6-address\x03\0\x08\
\x01q\x02\x04ipv4\x01\x07\0\x04ipv6\x01\x09\0\x04\0\x0aip-address\x03\0\x0a\x01r\
\x02\x04port{\x07address\x07\x04\0\x13ipv4-socket-address\x03\0\x0c\x01r\x04\x04\
port{\x09flow-infoy\x07address\x09\x08scope-idy\x04\0\x13ipv6-socket-address\x03\
\0\x0e\x01q\x02\x04ipv4\x01\x0d\0\x04ipv6\x01\x0f\0\x04\0\x11ip-socket-address\x03\
\0\x10\x04\0\x0atcp-socket\x03\x01\x04\0\x0audp-socket\x03\x01\x01i\x12\x01j\x01\
\x14\x01\x03\x01@\x01\x0eaddress-family\x05\0\x15\x04\0\x19[static]tcp-socket.cr\
eate\x01\x16\x01h\x12\x01j\0\x01\x03\x01@\x02\x04self\x17\x0dlocal-address\x11\0\
\x18\x04\0\x17[method]tcp-socket.bind\x01\x19\x01@\x02\x04self\x17\x0eremote-add\
ress\x11\0\x18\x04\0\x20[async\x20method]tcp-socket.connect\x01\x1a\x01f\x01\x14\
\x01j\x01\x1b\x01\x03\x01@\x01\x04self\x17\0\x1c\x04\0\x19[method]tcp-socket.lis\
ten\x01\x1d\x01f\x01}\x01@\x02\x04self\x17\x04data\x1e\0\x18\x04\0\x1d[async\x20\
method]tcp-socket.send\x01\x1f\x01e\x01\x18\x01o\x02\x1e\x20\x01@\x01\x04self\x17\
\0!\x04\0\x1a[method]tcp-socket.receive\x01\"\x01j\x01\x11\x01\x03\x01@\x01\x04s\
elf\x17\0#\x04\0$[method]tcp-socket.get-local-address\x01$\x04\0%[method]tcp-soc\
ket.get-remote-address\x01$\x01@\x01\x04self\x17\0\x7f\x04\0#[method]tcp-socket.\
get-is-listening\x01%\x01@\x01\x04self\x17\0\x05\x04\0%[method]tcp-socket.get-ad\
dress-family\x01&\x01@\x02\x04self\x17\x05valuew\0\x18\x04\0*[method]tcp-socket.\
set-listen-backlog-size\x01'\x01j\x01\x7f\x01\x03\x01@\x01\x04self\x17\0(\x04\0)\
[method]tcp-socket.get-keep-alive-enabled\x01)\x01@\x02\x04self\x17\x05value\x7f\
\0\x18\x04\0)[method]tcp-socket.set-keep-alive-enabled\x01*\x01j\x01\x01\x01\x03\
\x01@\x01\x04self\x17\0+\x04\0+[method]tcp-socket.get-keep-alive-idle-time\x01,\x01\
@\x02\x04self\x17\x05value\x01\0\x18\x04\0+[method]tcp-socket.set-keep-alive-idl\
e-time\x01-\x04\0*[method]tcp-socket.get-keep-alive-interval\x01,\x04\0*[method]\
tcp-socket.set-keep-alive-interval\x01-\x01j\x01y\x01\x03\x01@\x01\x04self\x17\0\
.\x04\0'[method]tcp-socket.get-keep-alive-count\x01/\x01@\x02\x04self\x17\x05val\
uey\0\x18\x04\0'[method]tcp-socket.set-keep-alive-count\x010\x01j\x01}\x01\x03\x01\
@\x01\x04self\x17\01\x04\0\x20[method]tcp-socket.get-hop-limit\x012\x01@\x02\x04\
self\x17\x05value}\0\x18\x04\0\x20[method]tcp-socket.set-hop-limit\x013\x01j\x01\
w\x01\x03\x01@\x01\x04self\x17\04\x04\0*[method]tcp-socket.get-receive-buffer-si\
ze\x015\x04\0*[method]tcp-socket.set-receive-buffer-size\x01'\x04\0'[method]tcp-\
socket.get-send-buffer-size\x015\x04\0'[method]tcp-socket.set-send-buffer-size\x01\
'\x01i\x13\x01j\x016\x01\x03\x01@\x01\x0eaddress-family\x05\07\x04\0\x19[static]\
udp-socket.create\x018\x01h\x13\x01@\x02\x04self9\x0dlocal-address\x11\0\x18\x04\
\0\x17[method]udp-socket.bind\x01:\x01@\x02\x04self9\x0eremote-address\x11\0\x18\
\x04\0\x1a[method]udp-socket.connect\x01;\x01@\x01\x04self9\0\x18\x04\0\x1d[meth\
od]udp-socket.disconnect\x01<\x01p}\x01k\x11\x01@\x03\x04self9\x04data=\x0eremot\
e-address>\0\x18\x04\0\x1d[async\x20method]udp-socket.send\x01?\x01o\x02=\x11\x01\
j\x01\xc0\0\x01\x03\x01@\x01\x04self9\0\xc1\0\x04\0\x20[async\x20method]udp-sock\
et.receive\x01B\x01@\x01\x04self9\0#\x04\0$[method]udp-socket.get-local-address\x01\
C\x04\0%[method]udp-socket.get-remote-address\x01C\x01@\x01\x04self9\0\x05\x04\0\
%[method]udp-socket.get-address-family\x01D\x01@\x01\x04self9\01\x04\0([method]u\
dp-socket.get-unicast-hop-limit\x01E\x01@\x02\x04self9\x05value}\0\x18\x04\0([me\
thod]udp-socket.set-unicast-hop-limit\x01F\x01@\x01\x04self9\04\x04\0*[method]ud\
p-socket.get-receive-buffer-size\x01G\x01@\x02\x04self9\x05valuew\0\x18\x04\0*[m\
ethod]udp-socket.set-receive-buffer-size\x01H\x04\0'[method]udp-socket.get-send-\
buffer-size\x01G\x04\0'[method]udp-socket.set-send-buffer-size\x01H\x03\0&wasi:s\
ockets/types@0.3.0-rc-2025-09-16\x05\x17\x02\x03\0\x10\x0aip-address\x01B\x08\x02\
\x03\x02\x01\x18\x04\0\x0aip-address\x03\0\0\x01m\x06\x07unknown\x0daccess-denie\
d\x10invalid-argument\x11name-unresolvable\x1atemporary-resolver-failure\x1aperm\
anent-resolver-failure\x04\0\x0aerror-code\x03\0\x02\x01p\x01\x01j\x01\x04\x01\x03\
\x01@\x01\x04names\0\x05\x04\0\x18[async]resolve-addresses\x01\x06\x03\0/wasi:so\
ckets/ip-name-lookup@0.3.0-rc-2025-09-16\x05\x19\x01B\x05\x01p}\x01@\x01\x03lenw\
\0\0\x04\0\x10get-random-bytes\x01\x01\x01@\0\0w\x04\0\x0eget-random-u64\x01\x02\
\x03\0&wasi:random/random@0.3.0-rc-2025-09-16\x05\x1a\x01B\x05\x01p}\x01@\x01\x03\
lenw\0\0\x04\0\x19get-insecure-random-bytes\x01\x01\x01@\0\0w\x04\0\x17get-insec\
ure-random-u64\x01\x02\x03\0(wasi:random/insecure@0.3.0-rc-2025-09-16\x05\x1b\x01\
B\x03\x01o\x02ww\x01@\0\0\0\x04\0\x11get-insecure-seed\x01\x01\x03\0-wasi:random\
/insecure-seed@0.3.0-rc-2025-09-16\x05\x1c\x01B\x03\x01j\0\0\x01@\0\0\0\x04\0\x0a\
[async]run\x01\x01\x04\0\x20wasi:cli/run@0.3.0-rc-2025-09-16\x05\x1d\x04\0$wasi:\
cli/command@0.3.0-rc-2025-09-16\x04\0\x0b\x0d\x01\0\x07command\x03\0\0\0G\x09pro\
ducers\x01\x0cprocessed-by\x02\x0dwit-component\x070.239.0\x10wit-bindgen-rust\x06\
0.46.0";
        };
    };
}
#[doc(inline)]
pub use __export_command_impl as _export_command;
#[rustfmt::skip]
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.46.0:wasi:cli@0.3.0-rc-2025-09-16:command-with-all-of-its-exports-removed:encoded worldrust-wasip3-0.2.2+wasi-0.3.0-rc-2025-09-16-from-crates-io-command-world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 8243] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x95?\x01A\x02\x01A2\x01\
B\x0a\x01o\x02ss\x01p\0\x01@\0\0\x01\x04\0\x0fget-environment\x01\x02\x01ps\x01@\
\0\0\x03\x04\0\x0dget-arguments\x01\x04\x01ks\x01@\0\0\x05\x04\0\x0fget-initial-\
cwd\x01\x06\x03\0(wasi:cli/environment@0.3.0-rc-2025-09-16\x05\0\x01B\x03\x01j\0\
\0\x01@\x01\x06status\0\x01\0\x04\0\x04exit\x01\x01\x03\0!wasi:cli/exit@0.3.0-rc\
-2025-09-16\x05\x01\x01B\x02\x01m\x03\x02io\x15illegal-byte-sequence\x04pipe\x04\
\0\x0aerror-code\x03\0\0\x03\0\"wasi:cli/types@0.3.0-rc-2025-09-16\x05\x02\x02\x03\
\0\x02\x0aerror-code\x01B\x08\x02\x03\x02\x01\x03\x04\0\x0aerror-code\x03\0\0\x01\
f\x01}\x01j\0\x01\x01\x01e\x01\x03\x01o\x02\x02\x04\x01@\0\0\x05\x04\0\x0fread-v\
ia-stream\x01\x06\x03\0\"wasi:cli/stdin@0.3.0-rc-2025-09-16\x05\x04\x01B\x06\x02\
\x03\x02\x01\x03\x04\0\x0aerror-code\x03\0\0\x01f\x01}\x01j\0\x01\x01\x01@\x01\x04\
data\x02\0\x03\x04\0\x17[async]write-via-stream\x01\x04\x03\0#wasi:cli/stdout@0.\
3.0-rc-2025-09-16\x05\x05\x01B\x06\x02\x03\x02\x01\x03\x04\0\x0aerror-code\x03\0\
\0\x01f\x01}\x01j\0\x01\x01\x01@\x01\x04data\x02\0\x03\x04\0\x17[async]write-via\
-stream\x01\x04\x03\0#wasi:cli/stderr@0.3.0-rc-2025-09-16\x05\x06\x01B\x01\x04\0\
\x0eterminal-input\x03\x01\x03\0+wasi:cli/terminal-input@0.3.0-rc-2025-09-16\x05\
\x07\x01B\x01\x04\0\x0fterminal-output\x03\x01\x03\0,wasi:cli/terminal-output@0.\
3.0-rc-2025-09-16\x05\x08\x02\x03\0\x06\x0eterminal-input\x01B\x06\x02\x03\x02\x01\
\x09\x04\0\x0eterminal-input\x03\0\0\x01i\x01\x01k\x02\x01@\0\0\x03\x04\0\x12get\
-terminal-stdin\x01\x04\x03\0+wasi:cli/terminal-stdin@0.3.0-rc-2025-09-16\x05\x0a\
\x02\x03\0\x07\x0fterminal-output\x01B\x06\x02\x03\x02\x01\x0b\x04\0\x0fterminal\
-output\x03\0\0\x01i\x01\x01k\x02\x01@\0\0\x03\x04\0\x13get-terminal-stdout\x01\x04\
\x03\0,wasi:cli/terminal-stdout@0.3.0-rc-2025-09-16\x05\x0c\x01B\x06\x02\x03\x02\
\x01\x0b\x04\0\x0fterminal-output\x03\0\0\x01i\x01\x01k\x02\x01@\0\0\x03\x04\0\x13\
get-terminal-stderr\x01\x04\x03\0,wasi:cli/terminal-stderr@0.3.0-rc-2025-09-16\x05\
\x0d\x01B\x02\x01w\x04\0\x08duration\x03\0\0\x03\0%wasi:clocks/types@0.3.0-rc-20\
25-09-16\x05\x0e\x02\x03\0\x0b\x08duration\x01B\x0c\x02\x03\x02\x01\x0f\x04\0\x08\
duration\x03\0\0\x01w\x04\0\x07instant\x03\0\x02\x01@\0\0\x03\x04\0\x03now\x01\x04\
\x01@\0\0\x01\x04\0\x0eget-resolution\x01\x05\x01@\x01\x04when\x03\x01\0\x04\0\x11\
[async]wait-until\x01\x06\x01@\x01\x08how-long\x01\x01\0\x04\0\x0f[async]wait-fo\
r\x01\x07\x03\0/wasi:clocks/monotonic-clock@0.3.0-rc-2025-09-16\x05\x10\x01B\x05\
\x01r\x02\x07secondsw\x0bnanosecondsy\x04\0\x08datetime\x03\0\0\x01@\0\0\x01\x04\
\0\x03now\x01\x02\x04\0\x0eget-resolution\x01\x02\x03\0*wasi:clocks/wall-clock@0\
.3.0-rc-2025-09-16\x05\x11\x02\x03\0\x0d\x08datetime\x01BY\x02\x03\x02\x01\x12\x04\
\0\x08datetime\x03\0\0\x01w\x04\0\x08filesize\x03\0\x02\x01m\x08\x07unknown\x0cb\
lock-device\x10character-device\x09directory\x04fifo\x0dsymbolic-link\x0cregular\
-file\x06socket\x04\0\x0fdescriptor-type\x03\0\x04\x01n\x06\x04read\x05write\x13\
file-integrity-sync\x13data-integrity-sync\x14requested-write-sync\x10mutate-dir\
ectory\x04\0\x10descriptor-flags\x03\0\x06\x01n\x01\x0esymlink-follow\x04\0\x0ap\
ath-flags\x03\0\x08\x01n\x04\x06create\x09directory\x09exclusive\x08truncate\x04\
\0\x0aopen-flags\x03\0\x0a\x01w\x04\0\x0alink-count\x03\0\x0c\x01k\x01\x01r\x06\x04\
type\x05\x0alink-count\x0d\x04size\x03\x15data-access-timestamp\x0e\x1bdata-modi\
fication-timestamp\x0e\x17status-change-timestamp\x0e\x04\0\x0fdescriptor-stat\x03\
\0\x0f\x01q\x03\x09no-change\0\0\x03now\0\0\x09timestamp\x01\x01\0\x04\0\x0dnew-\
timestamp\x03\0\x11\x01r\x02\x04type\x05\x04names\x04\0\x0fdirectory-entry\x03\0\
\x13\x01m$\x06access\x07already\x0ebad-descriptor\x04busy\x08deadlock\x05quota\x05\
exist\x0efile-too-large\x15illegal-byte-sequence\x0bin-progress\x0binterrupted\x07\
invalid\x02io\x0cis-directory\x04loop\x0etoo-many-links\x0cmessage-size\x0dname-\
too-long\x09no-device\x08no-entry\x07no-lock\x13insufficient-memory\x12insuffici\
ent-space\x0dnot-directory\x09not-empty\x0fnot-recoverable\x0bunsupported\x06no-\
tty\x0eno-such-device\x08overflow\x0dnot-permitted\x04pipe\x09read-only\x0cinval\
id-seek\x0etext-file-busy\x0ccross-device\x04\0\x0aerror-code\x03\0\x15\x01m\x06\
\x06normal\x0asequential\x06random\x09will-need\x09dont-need\x08no-reuse\x04\0\x06\
advice\x03\0\x17\x01r\x02\x05lowerw\x05upperw\x04\0\x13metadata-hash-value\x03\0\
\x19\x04\0\x0adescriptor\x03\x01\x01h\x1b\x01f\x01}\x01j\0\x01\x16\x01e\x01\x1e\x01\
o\x02\x1d\x1f\x01@\x02\x04self\x1c\x06offset\x03\0\x20\x04\0\"[method]descriptor\
.read-via-stream\x01!\x01@\x03\x04self\x1c\x04data\x1d\x06offset\x03\0\x1e\x04\0\
)[async\x20method]descriptor.write-via-stream\x01\"\x01@\x02\x04self\x1c\x04data\
\x1d\0\x1e\x04\0*[async\x20method]descriptor.append-via-stream\x01#\x01@\x04\x04\
self\x1c\x06offset\x03\x06length\x03\x06advice\x18\0\x1e\x04\0\x1f[async\x20meth\
od]descriptor.advise\x01$\x01@\x01\x04self\x1c\0\x1e\x04\0\"[async\x20method]des\
criptor.sync-data\x01%\x01j\x01\x07\x01\x16\x01@\x01\x04self\x1c\0&\x04\0\"[asyn\
c\x20method]descriptor.get-flags\x01'\x01j\x01\x05\x01\x16\x01@\x01\x04self\x1c\0\
(\x04\0![async\x20method]descriptor.get-type\x01)\x01@\x02\x04self\x1c\x04size\x03\
\0\x1e\x04\0![async\x20method]descriptor.set-size\x01*\x01@\x03\x04self\x1c\x15d\
ata-access-timestamp\x12\x1bdata-modification-timestamp\x12\0\x1e\x04\0\"[async\x20\
method]descriptor.set-times\x01+\x01f\x01\x14\x01o\x02,\x1f\x01@\x01\x04self\x1c\
\0-\x04\0'[async\x20method]descriptor.read-directory\x01.\x04\0\x1d[async\x20met\
hod]descriptor.sync\x01%\x01@\x02\x04self\x1c\x04paths\0\x1e\x04\0,[async\x20met\
hod]descriptor.create-directory-at\x01/\x01j\x01\x10\x01\x16\x01@\x01\x04self\x1c\
\00\x04\0\x1d[async\x20method]descriptor.stat\x011\x01@\x03\x04self\x1c\x0apath-\
flags\x09\x04paths\00\x04\0\x20[async\x20method]descriptor.stat-at\x012\x01@\x05\
\x04self\x1c\x0apath-flags\x09\x04paths\x15data-access-timestamp\x12\x1bdata-mod\
ification-timestamp\x12\0\x1e\x04\0%[async\x20method]descriptor.set-times-at\x01\
3\x01@\x05\x04self\x1c\x0eold-path-flags\x09\x08old-paths\x0enew-descriptor\x1c\x08\
new-paths\0\x1e\x04\0\x20[async\x20method]descriptor.link-at\x014\x01i\x1b\x01j\x01\
5\x01\x16\x01@\x05\x04self\x1c\x0apath-flags\x09\x04paths\x0aopen-flags\x0b\x05f\
lags\x07\06\x04\0\x20[async\x20method]descriptor.open-at\x017\x01j\x01s\x01\x16\x01\
@\x02\x04self\x1c\x04paths\08\x04\0$[async\x20method]descriptor.readlink-at\x019\
\x04\0,[async\x20method]descriptor.remove-directory-at\x01/\x01@\x04\x04self\x1c\
\x08old-paths\x0enew-descriptor\x1c\x08new-paths\0\x1e\x04\0\"[async\x20method]d\
escriptor.rename-at\x01:\x01@\x03\x04self\x1c\x08old-paths\x08new-paths\0\x1e\x04\
\0#[async\x20method]descriptor.symlink-at\x01;\x04\0'[async\x20method]descriptor\
.unlink-file-at\x01/\x01@\x02\x04self\x1c\x05other\x1c\0\x7f\x04\0'[async\x20met\
hod]descriptor.is-same-object\x01<\x01j\x01\x1a\x01\x16\x01@\x01\x04self\x1c\0=\x04\
\0&[async\x20method]descriptor.metadata-hash\x01>\x01@\x03\x04self\x1c\x0apath-f\
lags\x09\x04paths\0=\x04\0)[async\x20method]descriptor.metadata-hash-at\x01?\x03\
\0)wasi:filesystem/types@0.3.0-rc-2025-09-16\x05\x13\x02\x03\0\x0e\x0adescriptor\
\x01B\x07\x02\x03\x02\x01\x14\x04\0\x0adescriptor\x03\0\0\x01i\x01\x01o\x02\x02s\
\x01p\x03\x01@\0\0\x04\x04\0\x0fget-directories\x01\x05\x03\0,wasi:filesystem/pr\
eopens@0.3.0-rc-2025-09-16\x05\x15\x02\x03\0\x0c\x08duration\x01Bq\x02\x03\x02\x01\
\x16\x04\0\x08duration\x03\0\0\x01m\x0e\x07unknown\x0daccess-denied\x0dnot-suppo\
rted\x10invalid-argument\x0dout-of-memory\x07timeout\x0dinvalid-state\x14address\
-not-bindable\x0eaddress-in-use\x12remote-unreachable\x12connection-refused\x10c\
onnection-reset\x12connection-aborted\x12datagram-too-large\x04\0\x0aerror-code\x03\
\0\x02\x01m\x02\x04ipv4\x04ipv6\x04\0\x11ip-address-family\x03\0\x04\x01o\x04}}}\
}\x04\0\x0cipv4-address\x03\0\x06\x01o\x08{{{{{{{{\x04\0\x0cipv6-address\x03\0\x08\
\x01q\x02\x04ipv4\x01\x07\0\x04ipv6\x01\x09\0\x04\0\x0aip-address\x03\0\x0a\x01r\
\x02\x04port{\x07address\x07\x04\0\x13ipv4-socket-address\x03\0\x0c\x01r\x04\x04\
port{\x09flow-infoy\x07address\x09\x08scope-idy\x04\0\x13ipv6-socket-address\x03\
\0\x0e\x01q\x02\x04ipv4\x01\x0d\0\x04ipv6\x01\x0f\0\x04\0\x11ip-socket-address\x03\
\0\x10\x04\0\x0atcp-socket\x03\x01\x04\0\x0audp-socket\x03\x01\x01i\x12\x01j\x01\
\x14\x01\x03\x01@\x01\x0eaddress-family\x05\0\x15\x04\0\x19[static]tcp-socket.cr\
eate\x01\x16\x01h\x12\x01j\0\x01\x03\x01@\x02\x04self\x17\x0dlocal-address\x11\0\
\x18\x04\0\x17[method]tcp-socket.bind\x01\x19\x01@\x02\x04self\x17\x0eremote-add\
ress\x11\0\x18\x04\0\x20[async\x20method]tcp-socket.connect\x01\x1a\x01f\x01\x14\
\x01j\x01\x1b\x01\x03\x01@\x01\x04self\x17\0\x1c\x04\0\x19[method]tcp-socket.lis\
ten\x01\x1d\x01f\x01}\x01@\x02\x04self\x17\x04data\x1e\0\x18\x04\0\x1d[async\x20\
method]tcp-socket.send\x01\x1f\x01e\x01\x18\x01o\x02\x1e\x20\x01@\x01\x04self\x17\
\0!\x04\0\x1a[method]tcp-socket.receive\x01\"\x01j\x01\x11\x01\x03\x01@\x01\x04s\
elf\x17\0#\x04\0$[method]tcp-socket.get-local-address\x01$\x04\0%[method]tcp-soc\
ket.get-remote-address\x01$\x01@\x01\x04self\x17\0\x7f\x04\0#[method]tcp-socket.\
get-is-listening\x01%\x01@\x01\x04self\x17\0\x05\x04\0%[method]tcp-socket.get-ad\
dress-family\x01&\x01@\x02\x04self\x17\x05valuew\0\x18\x04\0*[method]tcp-socket.\
set-listen-backlog-size\x01'\x01j\x01\x7f\x01\x03\x01@\x01\x04self\x17\0(\x04\0)\
[method]tcp-socket.get-keep-alive-enabled\x01)\x01@\x02\x04self\x17\x05value\x7f\
\0\x18\x04\0)[method]tcp-socket.set-keep-alive-enabled\x01*\x01j\x01\x01\x01\x03\
\x01@\x01\x04self\x17\0+\x04\0+[method]tcp-socket.get-keep-alive-idle-time\x01,\x01\
@\x02\x04self\x17\x05value\x01\0\x18\x04\0+[method]tcp-socket.set-keep-alive-idl\
e-time\x01-\x04\0*[method]tcp-socket.get-keep-alive-interval\x01,\x04\0*[method]\
tcp-socket.set-keep-alive-interval\x01-\x01j\x01y\x01\x03\x01@\x01\x04self\x17\0\
.\x04\0'[method]tcp-socket.get-keep-alive-count\x01/\x01@\x02\x04self\x17\x05val\
uey\0\x18\x04\0'[method]tcp-socket.set-keep-alive-count\x010\x01j\x01}\x01\x03\x01\
@\x01\x04self\x17\01\x04\0\x20[method]tcp-socket.get-hop-limit\x012\x01@\x02\x04\
self\x17\x05value}\0\x18\x04\0\x20[method]tcp-socket.set-hop-limit\x013\x01j\x01\
w\x01\x03\x01@\x01\x04self\x17\04\x04\0*[method]tcp-socket.get-receive-buffer-si\
ze\x015\x04\0*[method]tcp-socket.set-receive-buffer-size\x01'\x04\0'[method]tcp-\
socket.get-send-buffer-size\x015\x04\0'[method]tcp-socket.set-send-buffer-size\x01\
'\x01i\x13\x01j\x016\x01\x03\x01@\x01\x0eaddress-family\x05\07\x04\0\x19[static]\
udp-socket.create\x018\x01h\x13\x01@\x02\x04self9\x0dlocal-address\x11\0\x18\x04\
\0\x17[method]udp-socket.bind\x01:\x01@\x02\x04self9\x0eremote-address\x11\0\x18\
\x04\0\x1a[method]udp-socket.connect\x01;\x01@\x01\x04self9\0\x18\x04\0\x1d[meth\
od]udp-socket.disconnect\x01<\x01p}\x01k\x11\x01@\x03\x04self9\x04data=\x0eremot\
e-address>\0\x18\x04\0\x1d[async\x20method]udp-socket.send\x01?\x01o\x02=\x11\x01\
j\x01\xc0\0\x01\x03\x01@\x01\x04self9\0\xc1\0\x04\0\x20[async\x20method]udp-sock\
et.receive\x01B\x01@\x01\x04self9\0#\x04\0$[method]udp-socket.get-local-address\x01\
C\x04\0%[method]udp-socket.get-remote-address\x01C\x01@\x01\x04self9\0\x05\x04\0\
%[method]udp-socket.get-address-family\x01D\x01@\x01\x04self9\01\x04\0([method]u\
dp-socket.get-unicast-hop-limit\x01E\x01@\x02\x04self9\x05value}\0\x18\x04\0([me\
thod]udp-socket.set-unicast-hop-limit\x01F\x01@\x01\x04self9\04\x04\0*[method]ud\
p-socket.get-receive-buffer-size\x01G\x01@\x02\x04self9\x05valuew\0\x18\x04\0*[m\
ethod]udp-socket.set-receive-buffer-size\x01H\x04\0'[method]udp-socket.get-send-\
buffer-size\x01G\x04\0'[method]udp-socket.set-send-buffer-size\x01H\x03\0&wasi:s\
ockets/types@0.3.0-rc-2025-09-16\x05\x17\x02\x03\0\x10\x0aip-address\x01B\x08\x02\
\x03\x02\x01\x18\x04\0\x0aip-address\x03\0\0\x01m\x06\x07unknown\x0daccess-denie\
d\x10invalid-argument\x11name-unresolvable\x1atemporary-resolver-failure\x1aperm\
anent-resolver-failure\x04\0\x0aerror-code\x03\0\x02\x01p\x01\x01j\x01\x04\x01\x03\
\x01@\x01\x04names\0\x05\x04\0\x18[async]resolve-addresses\x01\x06\x03\0/wasi:so\
ckets/ip-name-lookup@0.3.0-rc-2025-09-16\x05\x19\x01B\x05\x01p}\x01@\x01\x03lenw\
\0\0\x04\0\x10get-random-bytes\x01\x01\x01@\0\0w\x04\0\x0eget-random-u64\x01\x02\
\x03\0&wasi:random/random@0.3.0-rc-2025-09-16\x05\x1a\x01B\x05\x01p}\x01@\x01\x03\
lenw\0\0\x04\0\x19get-insecure-random-bytes\x01\x01\x01@\0\0w\x04\0\x17get-insec\
ure-random-u64\x01\x02\x03\0(wasi:random/insecure@0.3.0-rc-2025-09-16\x05\x1b\x01\
B\x03\x01o\x02ww\x01@\0\0\0\x04\0\x11get-insecure-seed\x01\x01\x03\0-wasi:random\
/insecure-seed@0.3.0-rc-2025-09-16\x05\x1c\x04\0Dwasi:cli/command-with-all-of-it\
s-exports-removed@0.3.0-rc-2025-09-16\x04\0\x0b-\x01\0'command-with-all-of-its-e\
xports-removed\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x07\
0.239.0\x10wit-bindgen-rust\x060.46.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen::rt::maybe_link_cabi_realloc();
}
